# Generated by Django 3.2.8 on 2021-10-25 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservice',
            name='slug',
            field=models.SlugField(default='df', max_length=40),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='delivery_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='del_methods', to='shop.deliveryservice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 14, 27, 41, 424958, tzinfo=utc)),
        ),
    ]
