# Generated by Django 3.2.8 on 2021-10-25 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211025_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_service',
            field=models.CharField(default='Новая почта', max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='appartment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='house',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='post_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 17, 59, 55, 25660, tzinfo=utc)),
        ),
    ]
