# Generated by Django 3.2.8 on 2021-10-25 18:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211025_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 18, 1, 55, 919723, tzinfo=utc)),
        ),
    ]
