# Generated by Django 3.2.8 on 2021-10-25 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211026_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='order_num',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 39, 1, 977884, tzinfo=utc)),
        ),
    ]
