# Generated by Django 3.2.8 on 2021-10-25 22:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211026_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_num',
            new_name='order_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 58, 52, 877940, tzinfo=utc)),
        ),
    ]
