# Generated by Django 3.2.8 on 2021-10-25 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211026_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 23, 4, 33, 73880, tzinfo=utc)),
        ),
    ]
